sudo: required
services:
  - docker

before_install:
  - docker build -t dockertravis/docker-react -f Dockerfile.dev .

script:
  -  docker run dockertravis/docker-react npm install react-scripts --save
  