sudo: required
services:
  - docker

before_install:
  - docker build -t dockertravis/docker-react -f Dockerfile.dev .

script:
  -  docker run dockertravis/docker-react npm install react-scripts --save

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-262276837591"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY