sudo: required
services:
  - docker

before_install:
  - docker build -t dockertravis/docker-react -f Dockerfile.dev .

script:
  -  docker run -e CI=true dockertravis/docker-react RUN chmod a+x /usr/src/app/node_modules/.bin/react-scripts

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-262276837591"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY